version: "3"
dotenv:
  - .env
vars:
  DB_DSN: ${DB_DSN}
  MIGRATION_DIR: ./services/gateway/internal/database/postgresql/migrations
tasks:
  # Check whether sqlc and goose are installed, install if not

  create-docker-network:
    cmds:
      - docker network create printing_service || true

  default:
    cmds:
      - echo "Checking for sqlc and goose installations..."
      - which sqlc || brew install sqlc
      - which goose || brew install goose

  test-gateway:
    cmds:
      - go test -v -race ./...
    dir: ./services/gateway

  test-validation-worker:
    cmds:
      - pytest -v
    dir: ./services/validation-worker

  validation-worker-benchmark-large-image:
    cmds:
      - python bench.py storage --file ./benchmark/large_image_4k.jpg --count 100
    dir: ./services/validation-worker

  validation-worker-benchmark-large-image-concurrent:
    cmds:
      - python bench.py storage --file ./benchmark/large_image_4k.jpg --count 100 -c 5
    dir: ./services/validation-worker

  validation-worker-benchmark-small-image:
    cmds:
      - python bench.py cpu --file ./benchmark/small_image.jpg --count 50
    dir: ./services/validation-worker

  validation-worker-benchmark-small-image-concurrent:
    cmds:
      - python bench.py cpu --file ./benchmark/small_image.jpg --count 50 -c 2
    dir: ./services/validation-worker

  migrate-up:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - echo "Applying migrations from {{.MIGRATION_DIR}} to database at {{.DB_DSN}}"
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" up

  # Roll back the last migration
  migrate-down:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" down

  # Check the current migration status
  migrate-status:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" status

  infra-down:
    dir: ./infrastructure
    cmds:
      - docker compose down --rmi local || true
  infra-restart:
    dotenv:
      - infrastructure/.env
    dir: ./infrastructure
    cmds:
      - docker compose down --rmi local || true
      - docker compose up -d
  infra-up:
    dir: ./infrastructure
    cmds:
      - docker compose up -d

  services-restart:
    cmds:
      - docker compose down --rmi local || true
      - docker compose up -d
