version: "3"
dotenv:
  - .env
vars:
  DB_DSN: ${DB_DSN}
  MIGRATION_DIR: ./services/gateway/internal/database/postgresql/migrations
tasks:
  # Check whether sqlc and goose are installed, install if not

  create-docker-network:
    cmds:
      - docker network create printing_service || true

  default:
    cmds:
      - echo "Checking for sqlc and goose installations..."
      - which sqlc || brew install sqlc
      - which goose || brew install goose

  test-gateway:
    cmds:
      - go test -v -race ./...
    dir: ./services/gateway

  test-indexer:
    cmds:
      - go test -v -race ./...
    dir: ./services/listings-worker

  test-validation-worker:
    cmds:
      - pytest -v
    dir: ./services/validation-worker

  test-all:
    cmds:
      - task: test-gateway
      - task: test-indexer
      - task: test-validation-worker

  validation-worker-benchmark-cpu:
    cmds:
      - python bench.py cpu --image-local ./examples/large_image_4k.jpg  --model-local ./examples/large_model.stl --count 50 -c 5
    dir: ./services/validation-worker

  validation-worker-benchmark-s3:
    cmds:
      - python bench.py storage --image-s3 benchmarks/large_image_4k.jpg --model-s3 benchmarks/large_model.stl --count 50 -c 5
    dir: ./services/validation-worker

  typesense-migrate:
    dir: ./infrastructure/typesense-migrations
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ../migrate_search_linux_amd64 cmd/main.go
      - GOOS=darwin GOARCH=amd64 go build -o ../migrate_search_darwin_amd64 cmd/main.go
  generate-sqlc:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - sqlc generate --file ./services/listings-worker/sqlc.yaml

  migrate-up:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - sqlc generate --file ./services/listings-worker/sqlc.yaml
      - echo "Applying migrations from {{.MIGRATION_DIR}} to database at {{.DB_DSN}}"
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" up

  # Roll back the last migration
  migrate-down:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" down

  # Check the current migration status
  migrate-status:
    cmds:
      - sqlc generate --file ./services/gateway/sqlc.yaml
      - goose -dir "{{.MIGRATION_DIR}}" postgres "{{.DB_DSN}}" status

  infra-down:
    dir: ./infrastructure
    cmds:
      - docker compose down --rmi local || true
  infra-restart:
    dotenv:
      - infrastructure/.env
    dir: ./infrastructure
    cmds:
      - docker compose down --rmi local || true
      - docker compose up -d
  infra-up:
    dir: ./infrastructure
    cmds:
      - docker compose up -d

  services-restart:
    cmds:
      - docker compose down --rmi local || true
      - docker compose up -d
