// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package listings_worker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetFilesByListingID(ctx context.Context, listingID pgtype.UUID) ([]ListingFile, error)
	GetListingByID(ctx context.Context, id pgtype.UUID) (GetListingByIDRow, error)
	// The worker calls this AFTER successfully pushing to Typesense
	MarkListingAsIndexed(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
