/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeMyListingsRouteImport } from './routes/(home)/my-listings'
import { Route as homeCreateListingRouteImport } from './routes/(home)/create-listing'
import { Route as homeListingsListingIdRouteImport } from './routes/(home)/listings/$listingId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeMyListingsRoute = homeMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeCreateListingRoute = homeCreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeListingsListingIdRoute = homeListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => homeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/terms': typeof TermsRoute
  '/create-listing': typeof homeCreateListingRoute
  '/my-listings': typeof homeMyListingsRoute
  '/': typeof homeIndexRoute
  '/listings/$listingId': typeof homeListingsListingIdRoute
}
export interface FileRoutesByTo {
  '/terms': typeof TermsRoute
  '/create-listing': typeof homeCreateListingRoute
  '/my-listings': typeof homeMyListingsRoute
  '/': typeof homeIndexRoute
  '/listings/$listingId': typeof homeListingsListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/terms': typeof TermsRoute
  '/(home)/create-listing': typeof homeCreateListingRoute
  '/(home)/my-listings': typeof homeMyListingsRoute
  '/(home)/': typeof homeIndexRoute
  '/(home)/listings/$listingId': typeof homeListingsListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/terms'
    | '/create-listing'
    | '/my-listings'
    | '/'
    | '/listings/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/terms'
    | '/create-listing'
    | '/my-listings'
    | '/'
    | '/listings/$listingId'
  id:
    | '__root__'
    | '/(home)'
    | '/terms'
    | '/(home)/create-listing'
    | '/(home)/my-listings'
    | '/(home)/'
    | '/(home)/listings/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/my-listings': {
      id: '/(home)/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof homeMyListingsRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/create-listing': {
      id: '/(home)/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof homeCreateListingRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/listings/$listingId': {
      id: '/(home)/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof homeListingsListingIdRouteImport
      parentRoute: typeof homeRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeCreateListingRoute: typeof homeCreateListingRoute
  homeMyListingsRoute: typeof homeMyListingsRoute
  homeIndexRoute: typeof homeIndexRoute
  homeListingsListingIdRoute: typeof homeListingsListingIdRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeCreateListingRoute: homeCreateListingRoute,
  homeMyListingsRoute: homeMyListingsRoute,
  homeIndexRoute: homeIndexRoute,
  homeListingsListingIdRoute: homeListingsListingIdRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
