// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gateway

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FileStatus string

const (
	FileStatusPENDING FileStatus = "PENDING"
	FileStatusVALID   FileStatus = "VALID"
	FileStatusINVALID FileStatus = "INVALID"
	FileStatusFAILED  FileStatus = "FAILED"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type FileType string

const (
	FileTypeMODEL FileType = "MODEL"
	FileTypeIMAGE FileType = "IMAGE"
)

func (e *FileType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileType(s)
	case string:
		*e = FileType(s)
	default:
		return fmt.Errorf("unsupported scan type for FileType: %T", src)
	}
	return nil
}

type NullFileType struct {
	FileType FileType `json:"file_type"`
	Valid    bool     `json:"valid"` // Valid is true if FileType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileType) Scan(value interface{}) error {
	if value == nil {
		ns.FileType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileType), nil
}

type ListingStatus string

const (
	ListingStatusPENDINGVALIDATION ListingStatus = "PENDING_VALIDATION"
	ListingStatusACTIVE            ListingStatus = "ACTIVE"
	ListingStatusREJECTED          ListingStatus = "REJECTED"
	ListingStatusHIDDEN            ListingStatus = "HIDDEN"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus `json:"listing_status"`
	Valid         bool          `json:"valid"` // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type Listing struct {
	ID                     pgtype.UUID        `json:"id"`
	SellerID               pgtype.UUID        `json:"seller_id"`
	SellerName             string             `json:"seller_name"`
	SellerUsername         string             `json:"seller_username"`
	SellerVerified         bool               `json:"seller_verified"`
	Title                  string             `json:"title"`
	Description            pgtype.Text        `json:"description"`
	PriceMinUnit           int64              `json:"price_min_unit"`
	Currency               string             `json:"currency"`
	Categories             []string           `json:"categories"`
	License                string             `json:"license"`
	ClientID               string             `json:"client_id"`
	TraceID                string             `json:"trace_id"`
	ThumbnailPath          pgtype.Text        `json:"thumbnail_path"`
	LastIndexedAt          pgtype.Timestamptz `json:"last_indexed_at"`
	Status                 NullListingStatus  `json:"status"`
	IsRemixingAllowed      bool               `json:"is_remixing_allowed"`
	ParentListingID        pgtype.UUID        `json:"parent_listing_id"`
	IsPhysical             bool               `json:"is_physical"`
	TotalWeightGrams       pgtype.Int4        `json:"total_weight_grams"`
	IsAssemblyRequired     bool               `json:"is_assembly_required"`
	IsHardwareRequired     bool               `json:"is_hardware_required"`
	HardwareRequired       []string           `json:"hardware_required"`
	IsMulticolor           bool               `json:"is_multicolor"`
	DimensionsMm           []byte             `json:"dimensions_mm"`
	RecommendedNozzleTempC pgtype.Int4        `json:"recommended_nozzle_temp_c"`
	RecommendedMaterials   []string           `json:"recommended_materials"`
	IsAiGenerated          bool               `json:"is_ai_generated"`
	AiModelName            pgtype.Text        `json:"ai_model_name"`
	LikesCount             pgtype.Int4        `json:"likes_count"`
	DownloadsCount         pgtype.Int4        `json:"downloads_count"`
	CommentsCount          pgtype.Int4        `json:"comments_count"`
	IsSaleActive           bool               `json:"is_sale_active"`
	SalePrice              pgtype.Numeric     `json:"sale_price"`
	SaleName               pgtype.Text        `json:"sale_name"`
	SaleEndTimestamp       pgtype.Timestamptz `json:"sale_end_timestamp"`
	SellerRatingAverage    pgtype.Numeric     `json:"seller_rating_average"`
	SellerTotalRatings     pgtype.Int4        `json:"seller_total_ratings"`
	SellerTotalSales       pgtype.Int4        `json:"seller_total_sales"`
	IsNsfw                 bool               `json:"is_nsfw"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type ListingFile struct {
	ID           pgtype.UUID        `json:"id"`
	ListingID    pgtype.UUID        `json:"listing_id"`
	FilePath     string             `json:"file_path"`
	FileType     FileType           `json:"file_type"`
	FileSize     pgtype.Int8        `json:"file_size"`
	Metadata     []byte             `json:"metadata"`
	Status       NullFileStatus     `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	IsGenerated  bool               `json:"is_generated"`
	SourceFileID pgtype.UUID        `json:"source_file_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
