// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gateway

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Note: 'categories' param must be passed as a string slice (text[]) in Go
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
	CreateListingFile(ctx context.Context, arg CreateListingFileParams) (ListingFile, error)
	GetFilesByListingID(ctx context.Context, listingID pgtype.UUID) ([]ListingFile, error)
	GetListingByID(ctx context.Context, id pgtype.UUID) (Listing, error)
	GetListingByIDAdmin(ctx context.Context, id pgtype.UUID) (Listing, error)
	GetListingsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetListingsByUserIDRow, error)
	// Finds all listings that are new OR have been updated since the last sync
	GetListingsForSync(ctx context.Context, limit int32) ([]Listing, error)
	// The worker calls this AFTER successfully pushing to Typesense
	MarkListingAsIndexed(ctx context.Context, id pgtype.UUID) error
	SoftDeleteFile(ctx context.Context, id pgtype.UUID) error
	SoftDeleteListing(ctx context.Context, arg SoftDeleteListingParams) (Listing, error)
	UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error)
}

var _ Querier = (*Queries)(nil)
